/* include/config.h.  Generated by configure.  */
#define HAVE_SYS_STATFS_H 1
#define HAVE_SYS_XATTR_H 1
/* #undef HAVE_SYS_EXTATTR_H */
#define HAVE_SYS_PARAM_H 1
#define HAVE_LGETXATTR 1
#define HAVE_LSETXATTR 1
#define HAVE_GETXATTR 1
#define HAVE_SETXATTR 1
/* #undef HAVE_GETATTRLIST */
/* #undef HAVE_SETATTRLIST */
/* #undef HAVE_CHFLAGS */
#define HAVE_STATVFS 1
#define HAVE_STATFS 1
/* #undef HAVE_EXT2FS_EXT2_FS_H */
/* #undef HAVE_STRUCT_STAT_ST_FLAGS */
/* #undef HAVE_STRUCT_STATVFS_F_FSTYPENAME */
/* #undef HAVE_STRUCT_STATFS_F_FSTYPENAME */
/* #undef HAVE_SYS_ACL_H */
/* #undef HAVE_LIBUTIL_H */
#define HAVE_ASPRINTF 1
/* #undef HAVE_LIBBZ2 */
#define HAVE_LCHOWN 1
/* #undef HAVE_LCHMOD */
#define UID_STRING RId32
#define UID_CAST (uint32_t)
#define GID_STRING PRId32
#define GID_CAST (uint32_t)
#define INO_STRING PRId64
#define INO_HEXSTRING PRIx64
#define INO_CAST (uint64_t)
#define DEV_STRING PRId64
#define DEV_HEXSTRING PRIx64
#define DEV_CAST (uint64_t)
